package com.tanjer.heartbeat.wsgenfile.test.pharmacy.saleCancelService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-19T11:21:08.893+05:30
 * Generated source version: 3.5.9
 *
 */
@WebServiceClient(name = "PharmacySaleCancelService",
                  wsdlLocation = "file:/C:/Users/USER/AppData/Local/Temp/tempdir15598451813776787987.tmp/PharmacySaleCancelService_1.wsdl",
                  targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleCancelService")
public class PharmacySaleCancelService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://dtts.sfda.gov.sa/PharmacySaleCancelService", "PharmacySaleCancelService");
    public static final QName PharmacySaleCancelService = new QName("http://dtts.sfda.gov.sa/PharmacySaleCancelService", "PharmacySaleCancelService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/USER/AppData/Local/Temp/tempdir15598451813776787987.tmp/PharmacySaleCancelService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PharmacySaleCancelService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/USER/AppData/Local/Temp/tempdir15598451813776787987.tmp/PharmacySaleCancelService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PharmacySaleCancelService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PharmacySaleCancelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PharmacySaleCancelService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PharmacySaleCancelService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PharmacySaleCancelService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PharmacySaleCancelService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PharmacySaleCancelService
     */
    @WebEndpoint(name = "PharmacySaleCancelService")
    public PharmacySaleCancelService getPharmacySaleCancelService() {
        return super.getPort(PharmacySaleCancelService, PharmacySaleCancelService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PharmacySaleCancelService
     */
    @WebEndpoint(name = "PharmacySaleCancelService")
    public PharmacySaleCancelService getPharmacySaleCancelService(WebServiceFeature... features) {
        return super.getPort(PharmacySaleCancelService, PharmacySaleCancelService.class, features);
    }

}
