package com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-19T12:22:31.451+05:30
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "http://dtts.sfda.gov.sa/DeactivationService", name = "DeactivationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeactivationService {

    @WebMethod
    @Action(input = "https://tandttest.sfda.gov.sa/ws/DeactivationService/DeactivationService/notifyDeactivationRequest", output = "https://tandttest.sfda.gov.sa/ws/DeactivationService/DeactivationService/notifyDeactivationResponse", fault = {@FaultAction(className = ServiceError.class, value = "https://tandttest.sfda.gov.sa/ws/DeactivationService/DeactivationService/notifyDeactivation/Fault/ServiceError")})
    @WebResult(name = "DeactivationServiceResponse", targetNamespace = "http://dtts.sfda.gov.sa/DeactivationService", partName = "DeactivationServiceResponse")
    public DeactivationServiceResponse notifyDeactivation(

        @WebParam(partName = "DeactivationServiceRequest", name = "DeactivationServiceRequest", targetNamespace = "http://dtts.sfda.gov.sa/DeactivationService")
        DeactivationServiceRequest deactivationServiceRequest
    ) throws ServiceError;
}
