package com.tanjer.heartbeat.wsgenfile.test.consumption.consumecancelservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-19T14:39:12.750+05:30
 * Generated source version: 3.5.9
 *
 */
@WebServiceClient(name = "ConsumeCancelService",
                  wsdlLocation = "${project.basedir}/src/main/resources/wsdl/tandtest/consumption/ConsumeCancelService_1.wsdl",
                  targetNamespace = "http://dtts.sfda.gov.sa/ConsumeCancelService")
public class ConsumeCancelService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://dtts.sfda.gov.sa/ConsumeCancelService", "ConsumeCancelService");
    public static final QName ConsumeCancelService = new QName("http://dtts.sfda.gov.sa/ConsumeCancelService", "ConsumeCancelService");
    static {
        URL url = null;
        try {
            url = new URL("${project.basedir}/src/main/resources/wsdl/tandtest/consumption/ConsumeCancelService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsumeCancelService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "${project.basedir}/src/main/resources/wsdl/tandtest/consumption/ConsumeCancelService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsumeCancelService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsumeCancelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumeCancelService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsumeCancelService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsumeCancelService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsumeCancelService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsumeCancelService
     */
    @WebEndpoint(name = "ConsumeCancelService")
    public ConsumeCancelService getConsumeCancelService() {
        return super.getPort(ConsumeCancelService, ConsumeCancelService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumeCancelService
     */
    @WebEndpoint(name = "ConsumeCancelService")
    public ConsumeCancelService getConsumeCancelService(WebServiceFeature... features) {
        return super.getPort(ConsumeCancelService, ConsumeCancelService.class, features);
    }

}
