<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://dtts.sfda.gov.sa/DeactivationCancelService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://dtts.sfda.gov.sa/DeactivationCancelService" name="DeactivationCancelService">
<types>
<xsd:schema>
<xsd:import namespace="http://dtts.sfda.gov.sa/DeactivationCancelService" schemaLocation="https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService?xsd=1"/>
</xsd:schema>
</types>
<message name="notifyDeactivationCancel">
<part name="DeactivationCancelServiceRequest" element="tns:DeactivationCancelServiceRequest"/>
</message>
<message name="notifyDeactivationCancelResponse">
<part name="DeactivationCancelServiceResponse" element="tns:DeactivationCancelServiceResponse"/>
</message>
<message name="ServiceError">
<part name="fault" element="tns:ServiceError"/>
</message>
<portType name="DeactivationCancelService">
<operation name="notifyDeactivationCancel">
<input wsam:Action="https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancelRequest" message="tns:notifyDeactivationCancel"/>
<output wsam:Action="https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancelResponse" message="tns:notifyDeactivationCancelResponse"/>
<fault message="tns:ServiceError" name="ServiceError" wsam:Action="https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancel/Fault/ServiceError"/>
</operation>
</portType>
<binding name="DeactivationCancelServiceBinding" type="tns:DeactivationCancelService">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="notifyDeactivationCancel">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault name="ServiceError">
<soap:fault name="ServiceError" use="literal"/>
</fault>
</operation>
</binding>
<service name="DeactivationCancelService">
<port name="DeactivationCancelService" binding="tns:DeactivationCancelServiceBinding">
<soap:address location="https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService"/>
</port>
</service>
</definitions>