package com.tanjer.heartbeat.wsgenfile.test.consumption.deactivationcancelservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-19T12:25:52.004+05:30
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "http://dtts.sfda.gov.sa/DeactivationCancelService", name = "DeactivationCancelService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeactivationCancelService {

    @WebMethod
    @Action(input = "https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancelRequest", output = "https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancelResponse", fault = {@FaultAction(className = ServiceError.class, value = "https://tandttest.sfda.gov.sa/ws/DeactivationCancelService/DeactivationCancelService/notifyDeactivationCancel/Fault/ServiceError")})
    @WebResult(name = "DeactivationCancelServiceResponse", targetNamespace = "http://dtts.sfda.gov.sa/DeactivationCancelService", partName = "DeactivationCancelServiceResponse")
    public DeactivationCancelServiceResponse notifyDeactivationCancel(

        @WebParam(partName = "DeactivationCancelServiceRequest", name = "DeactivationCancelServiceRequest", targetNamespace = "http://dtts.sfda.gov.sa/DeactivationCancelService")
        DeactivationCancelServiceRequest deactivationCancelServiceRequest
    ) throws ServiceError;
}
