package com.tanjer.heartbeat.wsgenfile.pharmacy.acceptDispatch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-18T15:20:48.284+05:30
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "http://dtts.sfda.gov.sa/AcceptDispatchService", name = "AcceptDispatchService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AcceptDispatchService {

    @WebMethod
    @Action(input = "https://tandttest.sfda.gov.sa/ws/AcceptDispatchService/AcceptDispatchService/notifyAcceptRequest", output = "https://tandttest.sfda.gov.sa/ws/AcceptDispatchService/AcceptDispatchService/notifyAcceptResponse", fault = {@FaultAction(className = ServiceError.class, value = "https://tandttest.sfda.gov.sa/ws/AcceptDispatchService/AcceptDispatchService/notifyAccept/Fault/ServiceError")})
    @WebResult(name = "AcceptDispatchServiceResponse", targetNamespace = "http://dtts.sfda.gov.sa/AcceptDispatchService", partName = "AcceptDispatchServiceResponse")
    public AcceptDispatchServiceResponse notifyAccept(

        @WebParam(partName = "AcceptDispatchServiceRequest", name = "AcceptDispatchServiceRequest", targetNamespace = "http://dtts.sfda.gov.sa/AcceptDispatchService")
        AcceptDispatchServiceRequest acceptDispatchServiceRequest
    ) throws ServiceError;
}
