package com.tanjer.heartbeat.wsgenfile.pharmacy.acceptService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-18T13:10:55.795+05:30
 * Generated source version: 3.5.9
 *
 */
@WebServiceClient(name = "AcceptService",
                  wsdlLocation = "file:/C:/Users/USER/AppData/Local/Temp/tempdir15490576381945689897.tmp/AcceptService_1.wsdl",
                  targetNamespace = "http://dtts.sfda.gov.sa/AcceptService")
public class AcceptService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://dtts.sfda.gov.sa/AcceptService", "AcceptService");
    public static final QName AcceptService = new QName("http://dtts.sfda.gov.sa/AcceptService", "AcceptService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/USER/AppData/Local/Temp/tempdir15490576381945689897.tmp/AcceptService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AcceptService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/USER/AppData/Local/Temp/tempdir15490576381945689897.tmp/AcceptService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AcceptService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AcceptService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcceptService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AcceptService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AcceptService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AcceptService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AcceptService
     */
    @WebEndpoint(name = "AcceptService")
    public AcceptService getAcceptService() {
        return super.getPort(AcceptService, AcceptService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcceptService
     */
    @WebEndpoint(name = "AcceptService")
    public AcceptService getAcceptService(WebServiceFeature... features) {
        return super.getPort(AcceptService, AcceptService.class, features);
    }

}
