package com.tanjer.heartbeat.wsgenfile.pharmacy.acceptService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-18T13:10:55.758+05:30
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "http://dtts.sfda.gov.sa/AcceptService", name = "AcceptService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AcceptService {

    @WebMethod
    @Action(input = "https://tandttest.sfda.gov.sa/ws/AcceptService/AcceptService/notifyAcceptRequest", output = "https://tandttest.sfda.gov.sa/ws/AcceptService/AcceptService/notifyAcceptResponse", fault = {@FaultAction(className = ServiceError.class, value = "https://tandttest.sfda.gov.sa/ws/AcceptService/AcceptService/notifyAccept/Fault/ServiceError")})
    @WebResult(name = "AcceptServiceResponse", targetNamespace = "http://dtts.sfda.gov.sa/AcceptService", partName = "AcceptServiceResponse")
    public AcceptServiceResponse notifyAccept(

        @WebParam(partName = "AcceptServiceRequest", name = "AcceptServiceRequest", targetNamespace = "http://dtts.sfda.gov.sa/AcceptService")
        AcceptServiceRequest acceptServiceRequest
    ) throws ServiceError;
}
