<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://dtts.sfda.gov.sa/PharmacySaleService"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://dtts.sfda.gov.sa/PharmacySaleService"
	name="PharmacySaleService">
	<types>
		<xsd:schema>
			<xsd:import
				namespace="http://dtts.sfda.gov.sa/PharmacySaleService"
				schemaLocation="https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService?xsd=1" />
		</xsd:schema>
	</types>
	<message name="notifyPharmacySale">
		<part name="PharmacySaleServiceRequest"
			element="tns:PharmacySaleServiceRequest" />
	</message>
	<message name="notifyPharmacySaleResponse">
		<part name="PharmacySaleServiceResponse"
			element="tns:PharmacySaleServiceResponse" />
	</message>
	<message name="ServiceError">
		<part name="fault" element="tns:ServiceError" />
	</message>
	<portType name="PharmacySaleService">
		<operation name="notifyPharmacySale">
			<input
				wsam:Action="https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySaleRequest"
				message="tns:notifyPharmacySale" />
			<output
				wsam:Action="https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySaleResponse"
				message="tns:notifyPharmacySaleResponse" />
			<fault message="tns:ServiceError" name="ServiceError"
				wsam:Action="https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySale/Fault/ServiceError" />
		</operation>
	</portType>
	<binding name="PharmacySaleServiceBinding"
		type="tns:PharmacySaleService">
		<soap:binding
			transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<operation name="notifyPharmacySale">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
			<fault name="ServiceError">
				<soap:fault name="ServiceError" use="literal" />
			</fault>
		</operation>
	</binding>
	<service name="PharmacySaleService">
		<port name="PharmacySaleService"
			binding="tns:PharmacySaleServiceBinding">
			<soap:address
				location="https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService" />
		</port>
	</service>
</definitions>