<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://dtts.sfda.gov.sa/ReturnService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://dtts.sfda.gov.sa/ReturnService" name="ReturnService">
<types>
<xsd:schema>
<xsd:import namespace="http://dtts.sfda.gov.sa/ReturnService" schemaLocation="https://tandttest.sfda.gov.sa/ws/ReturnService/ReturnService?xsd=1"/>
</xsd:schema>
</types>
<message name="notifyReturn">
<part name="ReturnServiceRequest" element="tns:ReturnServiceRequest"/>
</message>
<message name="notifyReturnResponse">
<part name="ReturnServiceResponse" element="tns:ReturnServiceResponse"/>
</message>
<message name="ServiceError">
<part name="fault" element="tns:ServiceError"/>
</message>
<portType name="ReturnService">
<operation name="notifyReturn">
<input wsam:Action="https://tandttest.sfda.gov.sa/ws/ReturnService/ReturnService/notifyReturnRequest" message="tns:notifyReturn"/>
<output wsam:Action="https://tandttest.sfda.gov.sa/ws/ReturnService/ReturnService/notifyReturnResponse" message="tns:notifyReturnResponse"/>
<fault message="tns:ServiceError" name="ServiceError" wsam:Action="https://tandttest.sfda.gov.sa/ws/ReturnService/ReturnService/notifyReturn/Fault/ServiceError"/>
</operation>
</portType>
<binding name="ReturnServiceBinding" type="tns:ReturnService">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="notifyReturn">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault name="ServiceError">
<soap:fault name="ServiceError" use="literal"/>
</fault>
</operation>
</binding>
<service name="ReturnService">
<port name="ReturnService" binding="tns:ReturnServiceBinding">
<soap:address location="https://tandttest.sfda.gov.sa/ws/ReturnService/ReturnService"/>
</port>
</service>
</definitions>