package com.tanjer.heartbeat.wsgenfile.pharmacy.saleService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-15T11:51:09.911+05:30
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleService", name = "PharmacySaleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PharmacySaleService {

    @WebMethod
    @Action(input = "https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySaleRequest", output = "https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySaleResponse", fault = {@FaultAction(className = ServiceError.class, value = "https://tandttest.sfda.gov.sa/ws/PharmacySaleService/PharmacySaleService/notifyPharmacySale/Fault/ServiceError")})
    @WebResult(name = "PharmacySaleServiceResponse", targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleService", partName = "PharmacySaleServiceResponse")
    public PharmacySaleServiceResponse notifyPharmacySale(

        @WebParam(partName = "PharmacySaleServiceRequest", name = "PharmacySaleServiceRequest", targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleService")
        PharmacySaleServiceRequest pharmacySaleServiceRequest
    ) throws ServiceError;
}
