package com.tanjer.heartbeat.wsgenfile.pharmacy.saleservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-15T11:51:09.944+05:30
 * Generated source version: 3.5.9
 *
 */
@SuppressWarnings("deprecation")
@WebServiceClient(name = "PharmacySaleService",
                  wsdlLocation = "${project.basedir}/src/main/resources/wsdl/tandtest/pharmacy/PharmacySaleService_1.wsdl",
                  targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleService")
public class PharmacySaleService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://dtts.sfda.gov.sa/PharmacySaleService", "PharmacySaleService");
    public static final QName PharmacySaleService = new QName("http://dtts.sfda.gov.sa/PharmacySaleService", "PharmacySaleService");
    static {
        URL url = null;
        try {
            url = new URL("${project.basedir}/src/main/resources/wsdl/tandtest/pharmacy/PharmacySaleService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PharmacySaleService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "${project.basedir}/src/main/resources/wsdl/tandtest/pharmacy/PharmacySaleService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PharmacySaleService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PharmacySaleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PharmacySaleService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PharmacySaleService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PharmacySaleService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PharmacySaleService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PharmacySaleService
     */
    @WebEndpoint(name = "PharmacySaleService")
    public PharmacySaleService getPharmacySaleService() {
        return super.getPort(PharmacySaleService, PharmacySaleService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PharmacySaleService
     */
    @WebEndpoint(name = "PharmacySaleService")
    public PharmacySaleService getPharmacySaleService(WebServiceFeature... features) {
        return super.getPort(PharmacySaleService, PharmacySaleService.class, features);
    }

}
