
package com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationCancelService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-19T14:28:26.670+05:30
 * Generated source version: 3.5.9
 */

@WebFault(name = "ServiceError", targetNamespace = "http://dtts.sfda.gov.sa/DeactivationCancelService")
public class ServiceError extends Exception {

    private com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationCancelService.FaultBean faultInfo;

    public ServiceError() {
        super();
    }

    public ServiceError(String message) {
        super(message);
    }

    public ServiceError(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ServiceError(String message, com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationCancelService.FaultBean serviceError) {
        super(message);
        this.faultInfo = serviceError;
    }

    public ServiceError(String message, com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationCancelService.FaultBean serviceError, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = serviceError;
    }

    public com.tanjer.heartbeat.wsgenfile.test.pharmacy.deactivationCancelService.FaultBean getFaultInfo() {
        return this.faultInfo;
    }
}
